language: cpp
addons:
  apt:
    packages:
      - cmake-data
      - cmake
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx

    - os: windows
