language: cpp
os:
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang  
addons:
  apt:
    packages:
      - cmake-data
      - cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
